# Generated by Django 2.2.6 on 2019-11-02 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='BotNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ChildParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_bot.Answer')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='chat_bot.BotNode')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_bot.BotNode')),
            ],
        ),
        migrations.AddField(
            model_name='botnode',
            name='childs',
            field=models.ManyToManyField(related_name='parent_node', through='chat_bot.ChildParent', to='chat_bot.BotNode'),
        ),
    ]
