# Generated by Django 2.2.6 on 2019-11-03 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botnode',
            old_name='question',
            new_name='value',
        ),
        migrations.AddField(
            model_name='botnode',
            name='is_start',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='botnode',
            name='childs',
            field=models.ManyToManyField(through='chat_bot.ChildParent', to='chat_bot.BotNode'),
        ),
        migrations.AlterField(
            model_name='childparent',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_parents', to='chat_bot.BotNode'),
        ),
        migrations.AlterField(
            model_name='childparent',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_childs', to='chat_bot.BotNode'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_bot.BotNode')),
            ],
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=32)),
                ('time', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_bot.BotNode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_bot.User')),
            ],
        ),
    ]
